name = "ConservativeRegridding"
uuid = "8e50ac2c-eb48-49bc-a402-07c87b949343"
license = "MIT"
version = "0.2.0"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>", "Milan Kloewer <milankloewer@gmx.de>", "Simone Silvestri <silvestri.simone0@gmail.com>", "and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GeometryOpsCore = "05efe853-fabf-41c8-927e-7063c8b9f013"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SciMLPublic = "431bcebd-1456-4ced-9d72-93c2757fff0b"
SortTileRecursiveTree = "746ee33f-1797-42c2-866d-db2fce69d14d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
Interfaces = "85a1e053-f937-4924-92a5-1367d23b7b87"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
RingGrids = "d1845624-ad4f-453b-8ff4-a8db365bf3a7"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[extensions]
ConservativeRegriddingClimaCoreExt = "ClimaCore"
ConservativeRegriddingInterfacesExt = "Interfaces"
ConservativeRegriddingOceananigansExt = "Oceananigans"
ConservativeRegriddingRingGridsExt = "RingGrids"
ConservativeRegriddingSpeedyWeatherExt = ["RingGrids", "SpeedyWeather"]

[compat]
ChunkSplitters = "3"
ClimaCore = "0.14"
DocStringExtensions = "0.8, 0.9"
Extents = "0.1"
GeoInterface = "1"
GeometryOps = "0.1.34"
GeometryOpsCore = "0.1.9"
LinearAlgebra = "1"
ProgressMeter = "1"
SciMLPublic = "1"
SortTileRecursiveTree = "0.1"
SparseArrays = "1"
StableTasks = "0.1.7"
StaticArrays = "1.9"
julia = "1.10"
