[deps]
ConservativeRegridding = "8e50ac2c-eb48-49bc-a402-07c87b949343"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[sources]
ConservativeRegridding = {path = ".."}
