[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
ConservativeRegridding = "8e50ac2c-eb48-49bc-a402-07c87b949343"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GeometryOpsCore = "05efe853-fabf-41c8-927e-7063c8b9f013"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"
SphericalSpatialTrees = "86b7679e-e8c0-4ea9-ad3d-baef5c69eb57"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WellKnownGeometry = "0f680547-7be7-4555-8820-bb198eeb646b"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"

[sources]
ConservativeRegridding = {path = ".."}
GeometryOps = {rev = "as/simple_spherical_intersection", url = "https://github.com/JuliaGeo/GeometryOps.jl"}
Oceananigans = {rev = "FPivot", url = "https://github.com/briochemc/Oceananigans.jl"}
SphericalSpatialTrees = {rev = "main", url = "https://github.com/meggart/SphericalSpatialTrees.jl"}
